
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_flujos = new javax.swing.JDialog();
        jb_iniciofin = new javax.swing.JButton();
        jb_decision = new javax.swing.JButton();
        jb_separadorv = new javax.swing.JButton();
        jb_separadorh = new javax.swing.JButton();
        jb_proceso = new javax.swing.JButton();
        jb_datos = new javax.swing.JButton();
        jp_flujo = new javax.swing.JPanel();
        jd_UML = new javax.swing.JDialog();
        jSeparator1 = new javax.swing.JSeparator();
        pp_menu1 = new javax.swing.JPopupMenu();
        cambiar_color = new javax.swing.JMenuItem();
        pp_menu2 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jb_iniciofin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in_fin.png"))); // NOI18N
        jb_iniciofin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciofinMouseClicked(evt);
            }
        });

        jb_decision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if.png"))); // NOI18N
        jb_decision.setToolTipText("");

        jb_separadorv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N

        jb_separadorh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separadorV.png"))); // NOI18N

        jb_proceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proceso.png"))); // NOI18N
        jb_proceso.setToolTipText("");

        jb_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datos.png"))); // NOI18N

        jp_flujo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_flujoLayout = new javax.swing.GroupLayout(jp_flujo);
        jp_flujo.setLayout(jp_flujoLayout);
        jp_flujoLayout.setHorizontalGroup(
            jp_flujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jp_flujoLayout.setVerticalGroup(
            jp_flujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_flujosLayout = new javax.swing.GroupLayout(jd_flujos.getContentPane());
        jd_flujos.getContentPane().setLayout(jd_flujosLayout);
        jd_flujosLayout.setHorizontalGroup(
            jd_flujosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_flujosLayout.createSequentialGroup()
                .addGroup(jd_flujosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_flujosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_flujosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_separadorh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_iniciofin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_decision, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_flujosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jb_separadorv, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jp_flujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jd_flujosLayout.setVerticalGroup(
            jd_flujosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_flujosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_flujosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_flujosLayout.createSequentialGroup()
                        .addComponent(jp_flujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jd_flujosLayout.createSequentialGroup()
                        .addComponent(jb_iniciofin)
                        .addGap(18, 18, 18)
                        .addComponent(jb_decision)
                        .addGap(18, 18, 18)
                        .addComponent(jb_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jb_datos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_separadorv)
                        .addGap(18, 18, 18)
                        .addComponent(jb_separadorh)
                        .addGap(81, 81, 81))))
        );

        javax.swing.GroupLayout jd_UMLLayout = new javax.swing.GroupLayout(jd_UML.getContentPane());
        jd_UML.getContentPane().setLayout(jd_UMLLayout);
        jd_UMLLayout.setHorizontalGroup(
            jd_UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_UMLLayout.setVerticalGroup(
            jd_UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        cambiar_color.setText("Cambiar Color");
        cambiar_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_colorActionPerformed(evt);
            }
        });
        pp_menu1.add(cambiar_color);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Visio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Crear Diagrama de flujos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 190, 90));

        jButton2.setText("Acerca de");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 190, 90));

        jButton3.setText("Crear Diagrama UML");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 190, 90));

        jButton4.setText("Acerca de");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 190, 90));

        jLabel3.setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JOptionPane.showMessageDialog(this, "Permite crear diagramas de flujo, descendentes, de seguimiento de informacion, de planeamiento de procesos y de prediccion de estructuras, contiene conectores y vinculos");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_flujos.pack();
        jd_flujos.setLocationRelativeTo(this);
        jd_flujos.setModal(true);
        jd_flujos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_iniciofinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciofinMouseClicked
        final JLabel jl_elegido;
        jl_elegido = new JLabel();
        jl_elegido.setOpaque(true);
        jl_elegido.setName("Label" + labelnum);
        jl_elegido.setBackground(Color.WHITE);
        labelnum++;
        jp_flujo.add(jl_elegido);
        jl_elegido.setLocation(10, 200);
        jl_elegido.setIcon(new ImageIcon(".\\UML\\in_fin.png"));
        jl_elegido.setText("");
        jl_elegido.setMaximumSize(new java.awt.Dimension(100, 100));
        jl_elegido.setMinimumSize(new Dimension(100, 100));
        jl_elegido.setLocation(new Point(20, 20));
        jl_elegido.setPreferredSize(new Dimension(50, 50));
        jl_elegido.setSize(100, 65);
        //agrega un label al panel

        //para poder mover un label seleccionado
        jl_elegido.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                seleccionado = jl_elegido;
                jl_elegido.setLocation(jl_elegido.getLocation().x + evt.getX() - jl_elegido.getWidth() / 2,
                        jl_elegido.getLocation().y + evt.getY() - jl_elegido.getHeight() / 2);
            }
        });

        //para sacar el pop up menu con las opciones que tiene el label seleccionado
        jl_elegido.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                seleccionado = jl_elegido;
                if (evt.isMetaDown()) {
                    seleccionado = jl_elegido;
                    pp_menu1.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                seleccionado = jl_elegido;
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                seleccionado = jl_elegido;
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                seleccionado = jl_elegido;
            }

            @Override
            public void mouseExited(MouseEvent e) {
                seleccionado = jl_elegido;
            }
        });


    }//GEN-LAST:event_jb_iniciofinMouseClicked

    private void cambiar_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_colorActionPerformed

        seleccionado.setBackground(JColorChooser.showDialog(jd_flujos, "Color?", Color.yellow));

    }//GEN-LAST:event_cambiar_colorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cambiar_color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_datos;
    private javax.swing.JButton jb_decision;
    private javax.swing.JButton jb_iniciofin;
    private javax.swing.JButton jb_proceso;
    private javax.swing.JButton jb_separadorh;
    private javax.swing.JButton jb_separadorv;
    private javax.swing.JDialog jd_UML;
    private javax.swing.JDialog jd_flujos;
    private javax.swing.JPanel jp_flujo;
    private javax.swing.JPopupMenu pp_menu1;
    private javax.swing.JPopupMenu pp_menu2;
    // End of variables declaration//GEN-END:variables
    int labelnum = 0;
    JLabel seleccionado = null;
}
